sudo: required
language: python
servies:
  - docker

before_install:
  - pip install awscli

jobs:
  include:
    - stage: build
      script:
        - docker build Ranking/ -t latest
    - stage: test
      script:
        - echo 'hello world'
