sudo: required
language: python
servies:
  - docker
env:
  global:
    WORKER_REPO=642498794654.dkr.ecr.us-east-2.amazonaws.com/ranking/worker

before_install:
  - pip install awscli

jobs:
  include:
    - stage: build
      script:
        - $(aws ecr get-login --region us-east-1)
        - docker build Ranking/ -t $WORKER_REPO:$TRAVIS_BRANCH-$TRAVIS_COMMIT
        - docker push $WORKER_REPO:$TRAVIS_BRANCH-$TRAVIS_COMMIT
    - stage: test
      script:
        - echo 'hello world'
