apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ranking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 642498794654.dkr.ecr.us-east-2.amazonaws.com/ranking/api:latest
          ports:
            - containerPort: 8000
