apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ranking
  labels:
    app: api
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31071
  selector:
    app: api
