apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ranking
  labels:
    app: api
spec:
  type: NodePort
  ports:
    - port: 31071
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: api
