apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ranking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gcr.io/personal-project-289714/ranking-app:202009232359
          volumeMounts:
            - name: db
              mountPath: /configs
          ports:
            - containerPort: 8000
      volumes:
        - name: db
          secret:
            secretName: postgres-ranking-0923
