apiVersion: batch/v1 # batch/v1beta
kind: Job #CronJob
metadata:
  name: data-pull-cron
  namespace: ranking
spec:
  template:
    spec:
      containers:
        - name: chess
          image: 642498794654.dkr.ecr.us-east-2.amazonaws.com/ranking/worker:master-59ff251fb1097a645cb93ef7ee0740602647cbed
      restartPolicy: OnFailure
# spec:
#   schedule: "0 0 1 * *"
#   jobTemplate:
#     spec:
#       containers:
#         - name: chess
#           image:
#       restartPolicy: OnFailure
