apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: data-pull-cron
  namespace: ranking
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: chess
              image: gcr.io/personal-project-289714/ranking-cron:202009232315
              volumeMounts:
                - name: db
                  mountPath: /configs
          restartPolicy: OnFailure
          volumes:
            - name: db
              secret:
                secretName: postgres-ranking-0923
