apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ranking
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31070
  selector:
    app: postgres
